num_users,user_id,start_time,end_time,status,details
90,25,1752685062.1417396,1752685062.1455934,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2050>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,69,1752685062.1942673,1752685062.1975734,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227700>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,49,1752685062.1714098,1752685062.1781018,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd720>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,58,1752685062.1813173,1752685062.1837049,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,65,1752685062.1909015,1752685062.196729,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227b80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,17,1752685062.1315765,1752685062.1592267,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162f50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,53,1752685062.1748214,1752685062.1841414,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90def80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,64,1752685062.1900802,1752685062.19691,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c21a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,32,1752685062.151267,1752685062.1520348,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161480>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,61,1752685062.185846,1752685062.189298,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fb250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,34,1752685062.153309,1752685062.1736617,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2e00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,57,1752685062.179979,1752685062.1938205,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227eb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,44,1752685062.166039,1752685062.1974795,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162980>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,63,1752685062.1893172,1752685062.1973104,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dce20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,54,1752685062.1755388,1752685062.209283,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92268c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,29,1752685062.1469836,1752685062.1957304,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd390>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,55,1752685062.177214,1752685062.183562,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,20,1752685062.134549,1752685062.1431959,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1de0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,52,1752685062.173685,1752685062.183346,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,43,1752685062.1647446,1752685062.1713698,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9d932b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,1,1752685062.1100032,1752685062.1119783,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163e20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,36,1752685062.155471,1752685062.1698327,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162650>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,4,1752685062.1139286,1752685062.1155083,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161000>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,18,1752685062.1325352,1752685062.1446395,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163220>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,42,1752685062.1626635,1752685062.1858213,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,7,1752685062.117503,1752685062.1180642,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2d70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,39,1752685062.1592686,1752685062.1639006,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,9,1752685062.1193268,1752685062.1228533,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3df0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,16,1752685062.12975,1752685062.182265,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,40,1752685062.1595013,1752685062.1635137,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd330>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,27,1752685062.1446617,1752685062.1565967,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dc760>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,6,1752685062.116819,1752685062.1174896,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c0d30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,71,1752685062.1988277,1752685062.20056,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f9d20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,30,1752685062.1485164,1752685062.151246,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91601f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,10,1752685062.1214626,1752685062.162637,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,50,1752685062.1722891,1752685062.1917453,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,67,1752685062.192949,1752685062.1978323,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fac20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,23,1752685062.1387243,1752685062.1484892,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162e60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,59,1752685062.182295,1752685062.190881,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,5,1752685062.1155248,1752685062.1168022,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1f00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,51,1752685062.1733902,1752685062.1869779,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227b80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,24,1752685062.1401007,1752685062.143683,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163430>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,2,1752685062.1120064,1752685062.112761,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162920>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,60,1752685062.1847584,1752685062.19424,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa320>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,35,1752685062.1542046,1752685062.1642432,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dee30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,68,1752685062.1938522,1752685062.197981,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92243a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,8,1752685062.118076,1752685062.118825,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c16f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,31,1752685062.150007,1752685062.1528492,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163370>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,45,1752685062.1663098,1752685062.1799247,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224d60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,38,1752685062.1579897,1752685062.1605601,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dc6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,66,1752685062.1917763,1752685062.1970713,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224940>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,21,1752685062.1357954,1752685062.1400745,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c0340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,74,1752685062.201709,1752685062.2117314,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8c70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,19,1752685062.1329854,1752685062.1339507,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,33,1752685062.1520493,1752685062.152644,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163310>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,37,1752685062.1566422,1752685062.1647065,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9160c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,11,1752685062.122882,1752685062.1262832,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c01c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,22,1752685062.137129,1752685062.149984,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91618d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,15,1752685062.1271431,1752685062.13421,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162b30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,3,1752685062.1132925,1752685062.1139135,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163100>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,47,1752685062.1679246,1752685062.177193,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd180>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,14,1752685062.1263063,1752685062.1329489,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2620>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,62,1752685062.187014,1752685062.1900585,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f93c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,56,1752685062.178136,1752685062.1812983,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226b60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,26,1752685062.143716,1752685062.1554537,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dde10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,13,1752685062.1260214,1752685062.1345186,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c01c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,48,1752685062.1698856,1752685062.1731608,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dddb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,73,1752685062.20058,1752685062.2057607,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162350>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,28,1752685062.145618,1752685062.146591,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90de950>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,46,1752685062.1671343,1752685062.172265,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224550>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,41,1752685062.1605844,1752685062.1671116,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd180>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,12,1752685062.1238391,1752685062.125995,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1f60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,81,1752685062.211775,1752685062.2153146,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd930>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,72,1752685062.1996162,1752685062.216292,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa8c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,78,1752685062.2057893,1752685062.2184074,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,77,1752685062.2054083,1752685062.2202241,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dde40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,80,1752685062.209317,1752685062.2206278,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dfb50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,70,1752685062.1986387,1752685062.2214143,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,79,1752685062.2078433,1752685062.2222505,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fb4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,83,1752685062.2163305,1752685062.2241538,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dee00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,90,1752685062.2222798,1752685062.2243226,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,82,1752685062.215345,1752685062.2246628,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,75,1752685062.203129,1752685062.2248633,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8d30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,86,1752685062.2192576,1752685062.225782,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163850>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,85,1752685062.218442,1752685062.2259688,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,84,1752685062.2174466,1752685062.226141,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,89,1752685062.2214375,1752685062.2263048,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dcd90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,76,1752685062.2040439,1752685062.2266278,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90de4a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,87,1752685062.220265,1752685062.2268016,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9d91960>: Failed to establish a new connection: [Errno 111] Connection refused'))"
90,88,1752685062.220668,1752685062.2269742,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90deb60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
