num_users,user_id,start_time,end_time,status,details
100,11,1752685072.2527921,1752685072.2538044,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fb7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,22,1752685072.270179,1752685072.2862163,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162a40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,50,1752685072.301778,1752685072.326807,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226b60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,58,1752685072.3107374,1752685072.319212,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3790>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,24,1752685072.2730203,1752685072.302115,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa020>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,32,1752685072.28126,1752685072.2947161,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2e00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,15,1752685072.256741,1752685072.261007,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dda80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,1,1752685072.2366233,1752685072.242218,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fbc40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,53,1752685072.3039868,1752685072.3132308,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9362d70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,29,1752685072.2777731,1752685072.2978146,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9225e40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,56,1752685072.3079765,1752685072.3148692,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fbf10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,47,1752685072.2984169,1752685072.3087711,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2e00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,2,1752685072.238661,1752685072.2426474,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c0670>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,83,1752685072.3388703,1752685072.3414698,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91cec50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,68,1752685072.3214731,1752685072.3324564,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90ddd50>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,23,1752685072.2718513,1752685072.2797863,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90de740>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,65,1752685072.3181212,1752685072.329176,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df880>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,9,1752685072.250671,1752685072.2527745,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f9b10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,27,1752685072.2756364,1752685072.2921903,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df670>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,18,1752685072.263517,1752685072.2666924,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dde10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,36,1752685072.2862365,1752685072.2998812,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,63,1752685072.3162386,1752685072.3195906,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd0c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,55,1752685072.3068926,1752685072.3275762,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92251e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,17,1752685072.2623868,1752685072.2665372,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162590>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,64,1752685072.3165562,1752685072.3301167,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dec80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,6,1752685072.2460616,1752685072.2671385,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91626b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,73,1752685072.3260818,1752685072.340372,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,46,1752685072.2978318,1752685072.3068612,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90ddae0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,51,1752685072.30214,1752685072.3241286,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227a00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,52,1752685072.3032773,1752685072.316535,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2b00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,10,1752685072.252119,1752685072.267526,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,57,1752685072.308793,1752685072.318981,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9363610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,33,1752685072.2823396,1752685072.2842531,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1a20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,60,1752685072.3132527,1752685072.321456,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162200>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,25,1752685072.2737496,1752685072.289171,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90def80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,49,1752685072.2999024,1752685072.3107026,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161a80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,48,1752685072.299243,1752685072.3052146,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,8,1752685072.2495513,1752685072.2536738,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8040>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,77,1752685072.33249,1752685072.336238,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224af0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,81,1752685072.3362575,1752685072.3416963,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91ce500>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,14,1752685072.2565646,1752685072.2657988,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9d918a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,43,1752685072.2952428,1752685072.3032596,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a93634f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,70,1752685072.3230264,1752685072.3265257,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9362800>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,62,1752685072.3149028,1752685072.3181038,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a93637f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,38,1752685072.2891943,1752685072.2992253,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,75,1752685072.330136,1752685072.337909,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226740>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,79,1752685072.334546,1752685072.3399968,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91cde70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,71,1752685072.3241472,1752685072.3406134,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9362d40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,54,1752685072.3052325,1752685072.3260283,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92250c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,16,1752685072.2613146,1752685072.2634947,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9160a30>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,82,1752685072.3379369,1752685072.3413305,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91ccb80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,74,1752685072.3291996,1752685072.341036,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c0af0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,69,1752685072.3223825,1752685072.3397691,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3c10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,12,1752685072.2546117,1752685072.2660453,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa170>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,41,1752685072.2922125,1752685072.2970355,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3c70>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,5,1752685072.244666,1752685072.246403,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91628f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,31,1752685072.2804968,1752685072.2910476,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9162920>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,20,1752685072.268128,1752685072.276716,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3310>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,21,1752685072.2692626,1752685072.2737265,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9160730>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,19,1752685072.2643628,1752685072.2681072,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dcac0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,34,1752685072.2833772,1752685072.2901964,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c15d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,28,1752685072.2767448,1752685072.3123887,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8970>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,26,1752685072.274588,1752685072.2823179,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9160820>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,40,1752685072.2910695,1752685072.29558,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f9db0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,3,1752685072.2401862,1752685072.2469783,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c01c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,37,1752685072.2879283,1752685072.2945204,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227a00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,76,1752685072.3311045,1752685072.3418465,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9224a60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,66,1752685072.3196158,1752685072.3339686,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91fa1a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,59,1752685072.3124127,1752685072.3223622,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9d919f0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,67,1752685072.3203115,1752685072.3310738,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f9a20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,45,1752685072.2970552,1752685072.3014524,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91cf280>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,7,1752685072.2486813,1752685072.2545726,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161210>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,44,1752685072.2956007,1752685072.2983925,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9361300>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,4,1752685072.2431135,1752685072.247138,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9d91d80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,13,1752685072.2556474,1752685072.2643175,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd570>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,30,1752685072.2798045,1752685072.2833552,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,35,1752685072.284273,1752685072.2948842,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1000>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,78,1752685072.3339865,1752685072.3408084,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9225fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,61,1752685072.3139622,1752685072.3271677,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90de620>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,39,1752685072.290216,1752685072.2952194,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92251e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,72,1752685072.3248007,1752685072.344277,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f86a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,80,1752685072.3352716,1752685072.345445,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91cdfc0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,85,1752685072.3432944,1752685072.3508594,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9161f90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,42,1752685072.2930567,1752685072.3522346,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9361e40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,84,1752685072.34258,1752685072.3525765,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9163610>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,93,1752685072.3522737,1752685072.3562012,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c1900>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,86,1752685072.3443244,1752685072.357068,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9361de0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,88,1752685072.3454754,1752685072.358175,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91ce110>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,98,1752685072.3571074,1752685072.3590548,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9227c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,92,1752685072.3509078,1752685072.3603702,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90df370>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,97,1752685072.3562305,1752685072.3605838,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9225540>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,99,1752685072.3582006,1752685072.360947,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226380>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,87,1752685072.34454,1752685072.3612955,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a90dd6c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,95,1752685072.3533845,1752685072.361538,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9226c80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,100,1752685072.3590822,1752685072.3616905,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a92242b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,89,1752685072.3461742,1752685072.3618176,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a91f8c10>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,91,1752685072.3483698,1752685072.3619595,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9362f20>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,96,1752685072.355389,1752685072.3622177,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c3460>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,94,1752685072.3526042,1752685072.3633807,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a87c2290>: Failed to establish a new connection: [Errno 111] Connection refused'))"
100,90,1752685072.347759,1752685072.3637648,CONNECTION_ERROR,"HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /process (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7410a9362f80>: Failed to establish a new connection: [Errno 111] Connection refused'))"
